- hosts: jenkins
  become: yes

  tasks:
    - name: Update system
      apt:
        update_cache: yes
        upgrade: dist

    - name: Install Java 21
      apt:
        name: openjdk-21-jdk
        state: present

    - name: Add Jenkins key
      get_url:
        url: https://pkg.jenkins.io/debian-stable/jenkins.io-2026.key
        dest: /usr/share/keyrings/jenkins-keyring.asc

    - name: Add Jenkins repo
      apt_repository:
        repo: "deb [signed-by=/usr/share/keyrings/jenkins-keyring.asc] https://pkg.jenkins.io/debian-stable binary/"
        state: present

    - name: Install Jenkins
      apt:
        name: jenkins
        state: present
        update_cache: yes

    - name: Enable Jenkins
      systemd:
        name: jenkins
        enabled: yes
        state: started

    - name: Install Docker
      apt:
        name: docker.io
        state: present

    - name: Enable Docker
      systemd:
        name: docker
        enabled: yes
        state: started

    - name: Add jenkins user to docker group
      user:
        name: jenkins
        groups: docker
        append: yes

    - name: Allow Jenkins port
      ufw:
        rule: allow
        port: 8080
        proto: tcp